import os
import smtplib
from email.message import EmailMessage
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def generate_pdf_report_bytes(user_message: str, property_details_text: str) -> bytes:
    """
    Generates a professionally styled PDF report in-memory as bytes.
    Used by the chat-based "email me the report" flow.
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []
    styles = getSampleStyleSheet()

    # ---- Custom Styles ----
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#1A365D"),
        spaceAfter=4,
        alignment=1  # Center
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#4A5568"),
        spaceAfter=16,
        alignment=1
    )

    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontSize=9.5,
        textColor=colors.HexColor("#2D3748"),
        leading=13,
        spaceAfter=8
    )

    small_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#A0AEC0"),
        alignment=1
    )

    # ---- 1. Header ----
    story.append(Paragraph("<b>AURA REAL ESTATE INTELLIGENCE</b>", title_style))
    story.append(Paragraph(
        f"Official Valuation & Market Report  •  Generated on: {datetime.now().strftime('%d %b %Y, %I:%M %p')}",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#1A365D"), spaceAfter=12))

    # ---- 2. User Query Context ----
    story.append(Paragraph("User Query Context", section_heading))

    query_data = [[Paragraph(f"<b>Query:</b> {user_message}", body_style)]]
    query_table = Table(query_data, colWidths=[520])
    query_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EDF2F7")),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#CBD5E0")),
    ]))
    story.append(query_table)
    story.append(Spacer(1, 14))

    # ---- 3. Dataset / Market Content ----
    story.append(Paragraph("Verified Dataset Records & Comparable Listings", section_heading))

    # Convert newlines to HTML breaks for ReportLab
    formatted_details = property_details_text.replace("\n", "<br/>")
    story.append(Paragraph(formatted_details, body_style))
    story.append(Spacer(1, 18))

    # ---- 4. Footer / Disclaimer ----
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#CBD5E0"), spaceAfter=8))
    story.append(Paragraph(
        "This document is generated automatically by AURA AI. "
        "Values are derived from historical MMR data models and are intended for analytical reference only.",
        small_style
    ))

    # Build PDF
    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data


def send_valuation_email(
    user_email: str,
    pdf_bytes: bytes,
    filename: str = "AURA_Valuation_Report.pdf",
    locality: str = None
) -> bool:
    """
    Sends the generated PDF bytes as an email attachment.
    Returns True on success, False on failure.
    """
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not sender_email or not sender_password:
        print("⚠️ SMTP credentials missing. Cannot send valuation email.")
        return False

    try:
        msg = EmailMessage()
        subject_locality = f" – {locality}" if locality else ""
        msg["Subject"] = f"Your Property Valuation Report{subject_locality} | AURA Estate"
        msg["From"] = sender_email
        msg["To"] = user_email

        msg.set_content(
            f"Hello,\n\n"
            f"Attached is your requested property valuation report generated by AURA Estate Intelligence.\n\n"
            f"You can download the PDF and review the detailed micro-market analysis.\n\n"
            f"Best regards,\n"
            f"AURA Estate Team"
        )

        msg.add_attachment(
            pdf_bytes,
            maintype="application",
            subtype="pdf",
            filename=filename
        )

        with smtplib.SMTP(smtp_server, smtp_port, timeout=20) as smtp:
            smtp.starttls()
            smtp.login(sender_email, sender_password)
            smtp.send_message(msg)

        print(f"✅ Valuation report emailed successfully to {user_email}")
        return True

    except Exception as e:
        print(f"❌ Failed to send valuation email to {user_email}: {e}")
        return False